// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Card.tsx";
import * as $$$$$$1 from "./sections/CardCadastroOfertas.tsx";
import * as $$$$$$2 from "./sections/CardContato.tsx";
import * as $$$$$$3 from "./sections/Footer.tsx";
import * as $$$$$$4 from "./sections/Hero.tsx";
import * as $$$$$$5 from "./sections/ParagraphList.tsx";
import * as $$$$$$6 from "./sections/SimpleTextList.tsx";
import * as $$$$$$7 from "./sections/Theme.tsx";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";

const manifest = {
  "sections": {
    "deco-sites/start/sections/Card.tsx": $$$$$$0,
    "deco-sites/start/sections/CardCadastroOfertas.tsx": $$$$$$1,
    "deco-sites/start/sections/CardContato.tsx": $$$$$$2,
    "deco-sites/start/sections/Footer.tsx": $$$$$$3,
    "deco-sites/start/sections/Hero.tsx": $$$$$$4,
    "deco-sites/start/sections/ParagraphList.tsx": $$$$$$5,
    "deco-sites/start/sections/SimpleTextList.tsx": $$$$$$6,
    "deco-sites/start/sections/Theme.tsx": $$$$$$7,
  },
  "apps": {
    "deco-sites/start/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/start/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/start",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
